# Generated by Django 5.2.17 on 2026-09-08 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('key', models.SlugField(help_text='Stable identifier, such as study-location or entry-qualification.', unique=True)),
                ('presentation', models.CharField(choices=[('fact', 'Overview row'), ('section', 'Detailed section')], default='fact', max_length=10)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True, help_text='Uncheck to hide this field on every public course page without deleting its values.')),
            ],
            options={
                'verbose_name': 'Course field',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='For example: Non-EU applicants residing outside Italy', max_length=200)),
                ('academic_year', models.CharField(help_text='For example: 2027/2028', max_length=20)),
                ('applicant_category', models.CharField(max_length=240)),
                ('application_start', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateTimeField(blank=True, help_text='Enter the date and local time in the time zone below.', null=True)),
                ('timezone', models.CharField(default='Europe/Rome', help_text='IANA time zone, e.g. Europe/Rome. Handles CET and summer time automatically.', max_length=64)),
                ('studies_commence', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('available_places', models.PositiveIntegerField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_calls', to='platform_app.course')),
            ],
            options={
                'ordering': ['order', 'application_start', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='platform_app.university')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Choose a department belonging to this university. Required for new courses.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='platform_app.department'),
        ),
        migrations.CreateModel(
            name='CourseFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Plain text. Paragraphs and line breaks are preserved.')),
                ('source_url', models.URLField(blank=True, help_text='Optional official page, fee schedule or requirements link.')),
                ('link_label', models.CharField(blank=True, max_length=160)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='platform_app.course')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='platform_app.coursefield')),
            ],
            options={
                'ordering': ['field__order', 'field_id'],
                'constraints': [models.UniqueConstraint(fields=('course', 'field'), name='unique_course_field_value')],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('university', 'title'), name='unique_university_department'),
        ),
    ]
