# Generated by Django 5.2.17 on 2026-09-19 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def seed_requirements(apps, schema_editor):
    Requirement=apps.get_model('platform_app','StudentChecklistRequirement')
    defaults=[
        ('passport','Passport bio page','A clear colour scan of the passport bio page.',True,'pdf,jpg,jpeg,png'),
        ('citizenship','Citizenship certificate','Nepali citizenship certificate, front and back if applicable.',True,'pdf,jpg,jpeg,png'),
        ('academic-transcript','Academic transcript','Transcript or consolidated marksheet for the previous qualification.',True,'pdf,jpg,jpeg,png'),
        ('degree-certificate','Degree or provisional certificate','Final certificate or provisional certificate for the previous qualification.',True,'pdf,jpg,jpeg,png'),
        ('english-test','English proficiency result','IELTS, PTE, TOEFL, Duolingo or accepted alternative, if available.',False,'pdf,jpg,jpeg,png'),
        ('cv','Curriculum vitae','An updated CV covering education, work and relevant experience.',False,'pdf'),
        ('motivation-letter','Motivation letter','A draft motivation letter for the selected programme.',False,'pdf,doc,docx'),
    ]
    for order,(key,title,description,required,extensions) in enumerate(defaults,1):
        Requirement.objects.get_or_create(key=key,defaults={'title':title,'description':description,'required':required,'accepted_extensions':extensions,'order':order})

def remove_requirements(apps, schema_editor):
    apps.get_model('platform_app','StudentChecklistRequirement').objects.filter(key__in=['passport','citizenship','academic-transcript','degree-certificate','english-test','cv','motivation-letter']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0014_university_logo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentChecklistRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('required', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('accepted_extensions', models.CharField(default='pdf,jpg,jpeg,png', help_text='Comma-separated file extensions.', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StudentChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('verified', 'Verified'), ('rejected', 'Needs replacement'), ('not_applicable', 'Not applicable')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('visible_to_student', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_items', to='platform_app.studentchecklistrequirement')),
            ],
            options={
                'ordering': ['requirement__order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=40)),
                ('nationality', models.CharField(default='Nepali', max_length=80)),
                ('passport_number', models.CharField(blank=True, max_length=80)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('citizenship_number', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
                ('municipality', models.CharField(blank=True, max_length=120)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=160)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=40)),
                ('highest_qualification', models.CharField(blank=True, max_length=120)),
                ('previous_degree', models.CharField(blank=True, max_length=200)),
                ('previous_institution', models.CharField(blank=True, max_length=240)),
                ('field_of_study', models.CharField(blank=True, max_length=160)),
                ('grading_system', models.CharField(blank=True, help_text='For example: percentage, 4.0 GPA or CGPA.', max_length=80)),
                ('overall_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('academic_history', models.JSONField(blank=True, default=list)),
                ('english_test', models.CharField(blank=True, help_text='For example: IELTS, PTE, TOEFL or Medium of Instruction.', max_length=80)),
                ('english_score', models.CharField(blank=True, max_length=80)),
                ('english_test_date', models.DateField(blank=True, null=True)),
                ('other_language', models.CharField(blank=True, max_length=80)),
                ('other_language_score', models.CharField(blank=True, max_length=80)),
                ('target_degree', models.CharField(blank=True, max_length=80)),
                ('target_disciplines', models.JSONField(blank=True, default=list)),
                ('preferred_cities', models.JSONField(blank=True, default=list)),
                ('profile_status', models.CharField(choices=[('incomplete', 'Profile incomplete'), ('submitted', 'Profile submitted'), ('under_review', 'Under review'), ('complete', 'Profile complete')], default='incomplete', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=80)),
                ('file', models.FileField(upload_to='private/student-documents/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Needs replacement')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='platform_app.studentchecklistitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='platform_app.studentprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='studentchecklistitem',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='platform_app.studentprofile'),
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('more_information', 'More information needed'), ('ready_to_apply', 'Ready to apply'), ('submitted_to_university', 'Submitted to university'), ('accepted', 'Accepted'), ('rejected', 'Not accepted'), ('withdrawn', 'Withdrawn')], default='draft', max_length=30)),
                ('student_note', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_applications', to='platform_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='platform_app.studentprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRecommendationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ai', 'AI course guidance'), ('admission_head', 'Admission Head review')], max_length=30)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In progress'), ('ready', 'Ready'), ('needs_information', 'Needs more information')], default='requested', max_length=30)),
                ('student_question', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_requests', to='platform_app.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=240)),
                ('rationale', models.TextField()),
                ('fit_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='platform_app.course')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='platform_app.studentrecommendationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplicationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('current', 'In progress'), ('complete', 'Complete'), ('blocked', 'Action needed')], default='pending', max_length=20)),
                ('visible_to_student', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='platform_app.studentapplication')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('application', 'key'), name='unique_application_stage')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentchecklistitem',
            constraint=models.UniqueConstraint(fields=('student', 'requirement'), name='unique_student_checklist_requirement'),
        ),
        migrations.RunPython(seed_requirements, remove_requirements),
    ]
