# Generated by Django 5.2.17 on 2026-09-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0015_studentchecklistrequirement_studentchecklistitem_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RemoveField(
            model_name='studentapplicationstage',
            name='application',
        ),
        migrations.RemoveField(
            model_name='studentchecklistitem',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='studentchecklistitem',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentdocument',
            name='checklist_item',
        ),
        migrations.RemoveField(
            model_name='studentdocument',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentrecommendationrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentrecommendation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentrecommendation',
            name='request',
        ),
        migrations.DeleteModel(
            name='StudentApplication',
        ),
        migrations.DeleteModel(
            name='StudentApplicationStage',
        ),
        migrations.DeleteModel(
            name='StudentChecklistRequirement',
        ),
        migrations.DeleteModel(
            name='StudentChecklistItem',
        ),
        migrations.DeleteModel(
            name='StudentDocument',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='StudentRecommendation',
        ),
        migrations.DeleteModel(
            name='StudentRecommendationRequest',
        ),
            ],
        ),
    ]
