# Generated by Django 5.2.17 on 2026-09-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0017_alter_article_source_url_alter_career_source_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_link',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='more_information',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='coursefieldvalue',
            name='source_url',
            field=models.URLField(blank=True, help_text='Optional official page, fee schedule or requirements link.', max_length=500),
        ),
    ]
