import json
from pathlib import Path
from datetime import date
from django.core.management.base import BaseCommand
from django.utils.text import slugify
from platform_app.models import *

def section(heading,body,kind='guidance',source_url=''):
    return dict(heading=heading,body=body,kind=kind,source_url=source_url)

def add(model,title,**kwargs):
    return model.objects.get_or_create(slug=slugify(title),defaults=dict(title=title,published=True,**kwargs))[0]

REGIONS=[
(1,'Piedmont',['Turin','Novara','Vercelli'],'EDISU Piemonte','https://www.edisu.piemonte.it/','Alpine weekends, elegant arcades and a strong engineering tradition.'),
(2,'Aosta Valley',['Aosta'],'Regione Valle d’Aosta','https://www.regione.vda.it/','A compact alpine region with French and Italian influences.'),
(3,'Lombardy',['Milan','Pavia','Bergamo','Brescia'],'University right-to-study offices (DSU)','https://www.regione.lombardia.it/','Design studios, global businesses and ambitious student communities.'),
(4,'Trentino-Alto Adige',['Trento','Bolzano'],'Opera Universitaria / Province of Bolzano','https://www.operauni.tn.it/','Research-led cities surrounded by the spectacular Dolomites.'),
(5,'Veneto',['Padua','Venice','Verona'],'ESU / university scholarship offices','https://www.esu.pd.it/','Historic university towns, Venetian canals and a connected regional economy.'),
(6,'Friuli-Venezia Giulia',['Trieste','Udine'],'ARDiS','https://www.ardis.fvg.it/','A meeting point of Italian, Central European and Adriatic cultures.'),
(7,'Liguria',['Genoa','Savona'],'ALiSEO','https://www.aliseo.liguria.it/','Maritime heritage and colourful coastal towns on the Italian Riviera.'),
(8,'Emilia-Romagna',['Bologna','Parma','Modena','Ferrara'],'ER.GO','https://www.er-go.it/','Lively university cities, a rich food culture and Italy’s Motor Valley.'),
(9,'Tuscany',['Florence','Pisa','Siena'],'DSU Toscana','https://www.dsu.toscana.it/','Renaissance cities, creative communities and centuries of scholarship.'),
(10,'Umbria',['Perugia','Terni'],'ADiSU Umbria','https://www.adisu.umbria.it/','Welcoming hill towns and green landscapes in the heart of Italy.'),
(11,'Marche',['Ancona','Urbino','Macerata','Camerino'],'ERDIS Marche','https://erdis.it/','Adriatic beaches and smaller university towns with a close-knit atmosphere.'),
(12,'Lazio',['Rome','Viterbo','Cassino'],'DiSCo Lazio','https://www.laziodisco.it/','An international student experience in and around the Italian capital.'),
(13,'Abruzzo',["L’Aquila",'Chieti','Pescara','Teramo'],'Local ADSU offices','https://www.adsuaq.org/','Mountain national parks and Adriatic cities with distinct student communities.'),
(14,'Molise',['Campobasso','Isernia'],'ESU Molise','https://www.regione.molise.it/','A quieter pace and small-city university life in southern Italy.'),
(15,'Campania',['Naples','Salerno','Benevento'],'ADISURC','https://www.adisurcampania.it/','Vibrant cities, Mediterranean culture and coastal landscapes.'),
(16,'Apulia',['Bari','Lecce','Foggia'],'ADISU Puglia','https://www.adisupuglia.it/','A sunny Adriatic region with growing academic and cultural communities.'),
(17,'Basilicata',['Potenza','Matera'],'ARDSU Basilicata','https://www.ardsubasilicata.it/','Small university settings and the extraordinary cave city of Matera.'),
(18,'Calabria',['Rende','Catanzaro','Reggio Calabria'],'University / regional right-to-study offices','https://www.unical.it/','Campus communities between mountains and the Mediterranean.'),
(19,'Sicily',['Palermo','Catania','Messina'],'Local ERSU offices','https://www.ersupalermo.it/','Island life with layered history, energetic cities and coastal adventures.'),
(20,'Sardinia',['Cagliari','Sassari'],'ERSU Cagliari / ERSU Sassari','https://www.ersucagliari.it/','An island study experience with distinctive traditions and beautiful coastline.')]
UNIS=[
('University of Bologna',8,'Bologna','https://www.unibo.it/en',44.496,11.354,['Business','Engineering','Humanities'],True,'Founded in 1088, Bologna is widely recognised as the oldest university in the Western world.'),
('Sapienza University of Rome',12,'Rome','https://www.uniroma1.it/en',41.903,12.516,['Medicine','Engineering','Humanities'],True,'A large public research university in Rome, founded in 1303.'),
('University of Padua',5,'Padua','https://www.unipd.it/en/',45.407,11.877,['Science','Medicine','Business'],True,'Founded in 1222, Padua has a long tradition of teaching and research.'),
('Politecnico di Milano',3,'Milan','https://www.polimi.it/en',45.478,9.228,['Engineering','Architecture','Design'],True,'A technical university specialising in engineering, architecture and design.'),
('University of Turin',1,'Turin','https://en.unito.it/',45.07,7.688,['Business','Science','Humanities'],True,'A public university at the heart of Piedmont’s capital.'),
('University of Aosta Valley',2,'Aosta','https://www.univda.it/',45.737,7.32,['Education','Business'],False,'A university in the bilingual alpine region of Aosta Valley.'),
('University of Trento',4,'Trento','https://www.unitn.it/en',46.067,11.15,['Engineering','Science'],True,'A research university based in Trento and Rovereto.'),
('University of Trieste',6,'Trieste','https://www.units.it/en',45.658,13.792,['Science','Engineering'],True,'A public university in the Adriatic city of Trieste.'),
('University of Genoa',7,'Genoa','https://unige.it/en',44.415,8.926,['Engineering','Business'],True,'A public university in the maritime city of Genoa.'),
('University of Florence',9,'Florence','https://www.unifi.it/en',43.778,11.259,['Architecture','Humanities'],True,'A public research university in Tuscany’s capital.'),
('University of Perugia',10,'Perugia','https://www.unipg.it/en/',43.116,12.386,['Science','Business'],True,'A historic public university in central Italy.'),
('University of Camerino',11,'Camerino','https://www.unicam.it/',43.135,13.068,['Science','Architecture'],True,'A university in the hill town of Camerino.'),
('University of L’Aquila',13,'L’Aquila','https://www.univaq.it/',42.349,13.399,['Engineering','Science'],True,'A public research university in Abruzzo.'),
('University of Molise',14,'Campobasso','https://www.unimol.it/',41.552,14.66,['Business','Science'],False,'A public university with locations across Molise.'),
('University of Naples Federico II',15,'Naples','https://www.unina.it/',40.847,14.257,['Engineering','Medicine'],True,'A historic public university in Naples.'),
('University of Bari Aldo Moro',16,'Bari','https://www.uniba.it/en',41.12,16.869,['Business','Medicine'],True,'A public university in Apulia’s capital.'),
('University of Basilicata',17,'Potenza','https://www.unibas.it/',40.637,15.805,['Engineering','Science'],False,'A public university based in Potenza and Matera.'),
('University of Calabria',18,'Rende','https://www.unical.it/',39.363,16.226,['Engineering','Science'],True,'A campus university in Rende, near Cosenza.'),
('University of Palermo',19,'Palermo','https://www.unipa.it/',38.105,13.35,['Business','Engineering'],True,'A public university in the Sicilian capital.'),
('University of Cagliari',20,'Cagliari','https://www.unica.it/',39.217,9.114,['Science','Business'],True,'A public university in southern Sardinia.')]
VERIFIED_COURSES=[
('Animal Care','animal-care','Department of Comparative Biomedicine and Food Science',"Bachelor's degree",'Animal science and welfare','Italy, Legnaro (Padua)',"Bachelor's degree, full-time",'3 years (180 ECTS)','English','https://agrariamedicinaveterinaria.unipd.it/en/courses/bachelors-first-cycle-and-masters-second-cycle-degrees/animal-care','A bachelor’s programme focused on animal management, welfare, behaviour, conservation and husbandry practices.'),
('Biology of Human and Environmental Health','biology-human-environmental-health','Department of Biomedical Sciences',"Bachelor's degree",'Biology and environmental health','Italy, Padua',"Bachelor's degree, full-time",'3 years (180 ECTS)','English','https://www.unipd.it/en/biology-human-environmental-health','An interdisciplinary programme covering the biological foundations of human health and interactions between people and the environment.'),
('Earth and Climate Dynamics','earth-climate-dynamics','Department of Geosciences',"Bachelor's degree",'Earth sciences and climate','Italy, Padua',"Bachelor's degree, full-time",'3 years (180 ECTS)','English','https://www.geoscienze.unipd.it/en/courses/bachelors-degree-earth-and-climate-dynamics-english','An English-taught bachelor’s programme in Earth system sciences, including solid Earth, oceans, climate, atmosphere and biosphere dynamics.'),
('Economics, Governance and Decision-Making','economics-governance-and-decision-making','Department of Economics and Management Marco Fanno',"Bachelor's degree",'Economics and governance','Italy, Padua',"Bachelor's degree, full-time",'3 years (180 ECTS)','English','https://www.economia.unipd.it/en/Bachelor%27s-degree-EGDM/bachelor%E2%80%99s-degree-economics-governance-and-decision-making','An English-taught bachelor’s programme combining economics, political science, philosophy and law with methodological and ethical reasoning.'),
('Information Engineering','information-engineering','Department of Information Engineering',"Bachelor's degree",'Information engineering','Italy, Padua',"Bachelor's degree, full-time",'3 years (180 ECTS)','English','https://www.unipd.it/en/corsi-laurea-lingua-inglese','An English-taught bachelor’s programme in information engineering listed in the University of Padua’s official English degree catalogue.'),
('Psychological Science','psychological-science','Department of General Psychology',"Bachelor's degree",'Psychology','Italy, Padua',"Bachelor's degree, full-time",'3 years (180 ECTS)','English','https://apply.unipd.it/courses/course/27-psychological-science','An English-taught bachelor’s programme covering foundational psychological theory, research methods, brain and behaviour, development and social psychology.'),
('Techniques and Methods in Psychological Science','techniques-methods-psychological-science','Department of General Psychology',"Bachelor's degree",'Psychology','Italy, Padua',"Bachelor's degree, online-delivered with exams in Padua",'3 years (180 ECTS)','English','https://www.unipd.it/corsi-di-laurea/techniques-and-methods-psychological-science','An English-taught psychology bachelor’s programme delivered online, with exams held in person at the University of Padua.'),
]
SERVICES={
'Study in Italy from Nepal':'Plan your study in Italy journey from Nepal with university selection, course matching, application planning, scholarships, visa preparation and support after arrival.',
'University Selection':'Find a university and course that fit your qualifications, interests and budget.',
'Application Support':'Build a clear application checklist and prepare your university submissions.',
'Visa Assistance':'Organise your student visa file and prepare for the consular process.',
'CIMEA & DOV Guidance':'Understand CIMEA comparability statements, Declaration of Value (DOV), qualification recognition and the documents your Italian university or visa pathway may request.',
'Document Legalization':'Prepare certificates, transcripts and academic documents for verification, legalization, embassy submission and Italian university applications.',
'Certified Translation':'Coordinate clear English and Italian translations for academic, civil and visa documents, with the correct certification and legalization pathway explained before submission.',
'IMAT & Entrance Test Preparation':'Prepare for IMAT, TOLC, CEnT-S, SAT and university-specific entrance tests with a study plan matched to your target course and current official call.',
'VFS Nepal & VFS Kolkata Guidance':'Prepare for the Italy student visa submission process through the current VFS route serving applicants from Nepal, including appointment planning, document order and centre instructions.',
'Geneva Attestation & Verification':'Understand Geneva attestation, document verification and the correct chain of authentication for Nepalese academic and civil documents used in an Italy application.',
'CAF / ISEE Scholarship Documentation':'Prepare the financial and family documents commonly requested for CAF, ISEE and regional right-to-study scholarship applications in Italy, with current authority requirements checked before submission.',
'All 20 Regions of Italy':'Explore all 20 regions of Italy, compare student cities, universities, scholarships, living costs and the kind of everyday life each region offers.',
'Accommodation':'Understand housing options, contracts, deposits and arrival arrangements.',
'Career Counseling':'Connect your academic choices with the work you want to do.',
'Scholarship Guidance':'Understand regional benefits, eligibility evidence and application steps.',
'Insurance Support':'Compare the coverage requirements relevant to your visa and stay.',
'Post-Arrival Services':'Settle into Italy with practical guidance from arrival to enrollment.',
'24/7 Support':'Ask about the available urgent-support arrangements before your departure.'}
CAREERS=[
('Student Success Advisor','Basundhara, Kathmandu · Hybrid','Full-time','Help students turn Italy study ambitions into clear, practical next steps. You will guide conversations, organise applications and stay close to each student’s journey.'),
('Content & Community Coordinator','Kathmandu','Full-time','Create useful Italy study guides, community stories and thoughtful social content for students preparing to move abroad.')]
STAGES=['Profile Evaluation','Career Counseling','University & Course Selection','University Shortlisting','Application Preparation','Document Preparation','University Application','Admission','Scholarship Application','Document Legalization','Pre-enrollment / Universitaly','Visa Documentation','Visa Appointment','Visa Interview Preparation','Visa Application','Visa Decision','Pre-Departure Preparation','Travel to Italy','Arrival in Italy','Accommodation Check-in','Codice Fiscale','Permesso di Soggiorno','University Enrollment','Bank/SIM/Residence Setup','Post-Arrival Support']
POST=['Airport pickup/support','Accommodation check-in','Codice Fiscale assistance','Permesso di Soggiorno guidance','SIM card assistance','Bank account guidance','University enrollment assistance','Residence registration guidance','Local transportation guidance','Student orientation','General settlement support']

class Command(BaseCommand):
    help='Seed initial editorial content without overwriting admin changes.'
    def handle(self,*args,**options):
        SiteSettings.objects.get_or_create(pk=1,defaults=dict(address='Basundhara, Kathmandu, Nepal',phone='+977 01-4971745',support_phone='+977 9709029676',email='headoffice@kashyapadvisors.com',office_hours='Sun–Fri, 9:00 AM–6:00 PM',announcement='Your Italy journey starts with a conversation. Book your personal consultation.',hero_description='Extraordinary universities. New possibilities. A life you’ll love. We guide you from Nepal to Italy, and every step in between.',footer_text='Your trusted guide from Nepal to a new chapter in Italy. Personal advice, thoughtful planning and support beyond arrival.'))
        geo=json.load(open(Path(__file__).resolve().parents[4]/'frontend/public/assets/italy-regions.geojson'))
        geos={x['properties']['reg_istat_code_num']:x['geometry'] for x in geo['features']}
        italy=Country.objects.get_or_create(name='Italy',defaults={'slug':'italy','code':'IT','published':True})[0]
        regions={}
        for code,name,cities,authority,url,desc in REGIONS:
            sch=add(Scholarship,authority,authority=authority,summary=f'Explore student benefits and calls relevant to {name}. Eligibility, amounts and deadlines depend on the current call and institution.',source_url=url,eligibility='Consult the current official call for nationality, household income, assets, academic merit and documentation conditions.',sections=[section('Before you apply','Check the current call, income-document requirements, translations and application portal. A benefit application does not guarantee an award.'),section('Official authority',f'Check the authority’s website and your university’s student-benefits office.',source_url=url)])
            regions[code]=add(Region,name,code=code,cities=cities,scholarship=sch,summary=desc,geometry=geos[code],living_cost='Build a city-specific budget with an advisor.',sections=[section('Student lifestyle',desc+' Join university societies, explore language exchanges and learn practical Italian for everyday life.'),section('Transportation','Compare local bus or tram passes, regional trains and the commute from your accommodation. Check student discounts with the local operator.'),section('Accommodation','Start with the university housing office and the regional scholarship authority. Compare contract terms, deposits, utilities and commute times before paying.'),section('Living costs','Prepare a monthly plan for rent, utilities, groceries, local travel, insurance and personal expenses. Costs vary by city and housing type. Request current quotations before making financial commitments.','estimate'),section('Places to explore','Start with '+', '.join(cities)+'. Your university’s international office can suggest local student activities.'),section('Popular subject areas','Browse the universities below and confirm individual programmes in the official course catalogue.')])
        for i,(name,code,city,url,lat,lon,disc,eng,overview) in enumerate(UNIS):
            add(University,name,country=italy,region=regions[code],city=city,website=url,latitude=lat,longitude=lon,disciplines=disc,degrees=['Bachelor’s','Master’s','PhD'],english_taught=eng,featured=i<4,summary=overview,source_url=url,tuition='Programme and income-assessment dependent. Check the current fee schedule.',image_url=['/assets/bologna.jpg','/assets/rome.jpg','/assets/padua.jpg','/assets/milan.jpg'][i%4],sections=[section('University overview',overview),section('History & academic community',overview+' Explore the university’s official history and campus information.',source_url=url),section('Courses & degree levels','Explore bachelor’s, master’s and doctoral calls in the official catalogue. Availability and teaching language vary by programme.',source_url=url),section('English-taught programmes','Check the language of instruction and accepted language certificates on the individual programme page.',source_url=url),section('Admission requirements','Each programme sets its academic prerequisites, language requirements and selection method. Prepare transcripts, qualification certificates and identification; confirm the exact list in the current call.',source_url=url),section('Application process','Select a programme, read its call, prepare the required evidence and submit through the university’s official application portal. Track requests for additional documents.'),section('Application deadlines','Deadlines differ by programme, intake and applicant category. Refer to the current programme call; no common university-wide deadline is assumed.',source_url=url),section('Tuition fees','Fees and reductions depend on the programme and applicable assessment rules. Consult the official fee schedule before budgeting.',source_url=url),section('Accommodation & living costs','Compare university residences and private rentals. Budget separately for deposits, rent, utilities, groceries, travel and personal expenses.','estimate'),section('Transportation & student life',f'Explore student organisations and international-office orientation in {city}. Check local transport passes and campus connections.'),section('Nearby cities & places to visit',', '.join(regions[code].cities)+'. Plan leisure travel around your course attendance requirements.')])
        padua=University.objects.get(slug='university-of-padua')
        for title,slug,department_title,degree,discipline,location,course_type,duration,language,source_url,summary in VERIFIED_COURSES:
            department,_=Department.objects.get_or_create(university=padua,title=department_title,defaults={'published':True})
            department.published=True
            department.save(update_fields=['published'])
            Course.objects.update_or_create(slug=slug,defaults=dict(
                title=title,summary=summary,degree=degree,discipline=discipline,
                study_location=location,course_type=course_type,nominal_duration=duration,
                study_language=language,source_url=source_url,university=padua,
                department=department,english_taught=True,published=True,
                reviewed_at=date(2026,9,19),course_link=source_url,
                additional_info='Verified against the official University of Padua source on 2026-09-19. Fees and admission deadlines are intentionally omitted until confirmed from the current official call.',
            ))
        for i,(name,summary) in enumerate(SERVICES.items()):
            items=[section('How we help',summary),section('Your next step','Bring your academic background and goals to a personal consultation. We will discuss the scope, timings and any service fees before you proceed.')]
            if name=='Study in Italy from Nepal':
                items=[section('Your route from Nepal to Italy',summary),section('Choose the right course and university','Compare bachelor’s, master’s and PhD options, English-taught programmes, admission requirements, tuition and application deadlines. Requirements vary by university and programme.'),section('Plan documents, CIMEA, DOV and visa steps','Create a programme-specific checklist for qualification documents, translations, legalization, CIMEA or Declaration of Value requests, Universitaly pre-enrolment and the Type D student visa pathway.'),section('Get support after arrival','Prepare accommodation, codice fiscale, permesso di soggiorno, university enrollment and the first practical steps of life in Italy.')]
            elif name=='CIMEA & DOV Guidance':
                items=[section('CIMEA and Declaration of Value explained',summary),section('CIMEA comparability','CIMEA statements and procedures depend on the receiving institution and the qualification. Check the current CIMEA platform requirements and confirm whether your selected university requests a comparability or verification service.',source_url='https://www.cimea.it/'),section('Declaration of Value (DOV)','The Italian diplomatic authority may issue a Declaration of Value for a foreign qualification. Requirements, appointment procedures and document formats can change, so confirm the current instructions for your jurisdiction.',source_url='https://ambkathmandu.esteri.it/en/'),section('Our document checklist','We help you map your Nepalese certificates, transcripts, translations, attestations and legalization steps to the current request from the university or consular office.')]
            elif name=='Document Legalization':
                items=[section('Legalization for Italy applications',summary),section('Start with the receiving authority','Ask your university, CIMEA, embassy or consular office which documents must be legalized, apostilled, verified or accompanied by a Declaration of Value. Do not rely on an old checklist.'),section('Academic and civil documents','Typical files may include certificates, transcripts, birth records, affidavits and financial documents. The correct route depends on the document, issuing authority and destination.'),section('A clear submission sequence','We help organise originals, copies, attestations, translations and appointment files so each document reaches the right authority in the required order.')]
            elif name=='Certified Translation':
                items=[section('Translation for Italian university and visa documents',summary),section('What may need translation','Academic certificates, transcripts, civil documents and financial evidence may need English or Italian translation depending on the receiving authority.'),section('Certification and legalization','Translation requirements differ between a university, CIMEA, the Italian Embassy and the visa application process. Confirm the required certification before ordering the final version.'),section('Quality check before submission','We help compare names, dates, grades, stamps and page references across the original and translated documents.')]
            elif name=='IMAT & Entrance Test Preparation':
                items=[section('Prepare for IMAT and Italian entrance tests',summary),section('IMAT, TOLC and CEnT-S','The current programme call determines the test, eligibility, registration window, syllabus, scoring and selection process. Check the official provider and ministry notices for the relevant academic year.',source_url='https://accessoprogrammato.mur.gov.it/'),section('A practical preparation plan','Start with a diagnostic test, map biology, chemistry, physics, mathematics, logic and reading skills, then practise under timed conditions.'),section('Registration and deadlines','Use the official registration portal and verify the test format, fee, identity documents, test centre and deadline before booking.',source_url='https://www.cisiaonline.it/en')]
            elif name=='VFS Nepal & VFS Kolkata Guidance':
                items=[section('Italy student visa support for Nepal applicants',summary),section('VFS Nepal and VFS Kolkata','Visa submission locations, appointment availability and jurisdiction rules can change. Check the current Italy visa instructions for Nepal and the centre assigned to your application before travelling.',source_url='https://visa.vfsglobal.com/'),section('Prepare your VFS appointment file','Organise passport, admission or pre-enrolment evidence, financial proof, insurance, accommodation, legalized and translated documents in the order requested by the current checklist.'),section('What we help with','We help you review the checklist, identify missing evidence, prepare questions and plan the submission. VFS receives documents; the competent consular authority decides the visa.')]
            elif name=='Geneva Attestation & Verification':
                items=[section('Geneva attestation for Italy applications',summary),section('Authentication chain','Confirm whether your document requires issuing-authority verification, Geneva attestation, embassy or consular legalization, translation, or another current form of recognition.'),section('Match the requirement','University admissions, CIMEA, DOV and visa applications may ask for different evidence. We help map the request to the exact document and authority before you submit.'),section('Avoid outdated checklists','Attestation rules and appointment procedures can change. Confirm the current instruction with the receiving university and the relevant Italian diplomatic authority.',source_url='https://ambkathmandu.esteri.it/en/')]
            elif name=='CAF / ISEE Scholarship Documentation':
                items=[section('CAF, ISEE and Italian scholarship paperwork',summary),section('What CAF and ISEE do','CAF offices can assist with declarations and ISEE documentation in Italy. A regional scholarship authority determines its own call, eligibility rules, deadlines and accepted evidence.'),section('Prepare family and financial evidence','Review household composition, income, assets, bank statements, translations, attestations and any required equivalent financial documentation before the scholarship deadline.'),section('Regional right-to-study benefits','Compare the current scholarship call for your university and region. Applications, accommodation benefits, meals and fee reductions depend on the published rules and available funds.')]
            elif name=='All 20 Regions of Italy':
                items=[section('All 20 regions of Italy for international students',summary),section('From Piedmont to Sardinia','Compare Piedmont, Aosta Valley, Lombardy, Trentino-Alto Adige, Veneto, Friuli-Venezia Giulia, Liguria, Emilia-Romagna, Tuscany, Umbria, Marche, Lazio, Abruzzo, Molise, Campania, Apulia, Basilicata, Calabria, Sicily and Sardinia.'),section('Choose by city, course and lifestyle','Explore universities, English-taught programmes, regional scholarships, living costs, transport and student communities before choosing where to apply.'),section('Build your shortlist','Use the interactive region guide and university directory, then confirm every course requirement and deadline on the official university website.')]
            if name=='Post-Arrival Services':items=[section(x,'We help you understand the relevant local process, prepare questions and find the responsible office. Availability and arrangements are confirmed during consultation.') for x in POST]
            add(Page,name,kind='service',summary=summary,order=i,sections=items)
        for i,(title,location,employment,summary) in enumerate(CAREERS):
            add(Career,title,location=location,employment_type=employment,summary=summary,order=i,sections=[section('The role',summary),section('What you will do','Work closely with students, advisors and university information. Keep communication clear, maintain accurate records and help each student understand their next action.'),section('How to apply','Send your CV and a short cover letter through the application form on this page. We review applications as roles remain open.')])
        benefits=[('Globally recognised education','Explore established universities and internationally connected research communities.'),('Affordable study options','Public universities offer varied fee structures and income-based reductions where eligible.'),('Scholarships that open doors','Discover regional benefits and university awards, with eligibility explained clearly.'),('Learn in English','Find English-taught programmes while building your Italian language skills.'),('A life beyond the classroom','Art, history, food and a vibrant student lifestyle become part of your everyday.'),('A European perspective','Meet international peers and explore academic and professional opportunities.')]
        for i,(name,summary) in enumerate(benefits):add(Page,name,kind='benefit',summary=summary,order=i)
        for i,name in enumerate(['Italy-focused expertise','Personalized counseling','End-to-end application support','Scholarship guidance','Visa assistance','Transparent process','Pre-departure support','Post-arrival support','Long-term student assistance']):add(Page,'Why Kashyap: '+name,kind='advantage',summary=name,order=i)
        for i,title in enumerate(STAGES):add(Page,'Journey: '+title,kind='journey',order=i,summary=title,sections=[section(title,{'Profile Evaluation':'Share your qualifications, results, interests and study goals so we can identify suitable next steps.','Pre-enrollment / Universitaly':'Where required for your student visa pathway, submit pre-enrollment through the official Universitaly portal. University validation does not guarantee a visa.','Permesso di Soggiorno':'Consult the official arrival guidance promptly and complete the residence permit process within the applicable deadline.','Visa Decision':'The competent diplomatic or consular authority decides the application. Admission and pre-enrollment do not guarantee approval.'}.get(title,'Work with your advisor to prepare the documents, practical arrangements and next actions for this stage. The exact order and requirements depend on your university and personal situation.'),source_url='https://www.universitaly.it/en/studenti-stranieri' if 'Visa' in title or 'Universitaly' in title else '')])
        from platform_app.test_content import TEST_PAGES, REVIEWED
        for order, guide in enumerate(TEST_PAGES):
            Page.objects.get_or_create(slug=guide['slug'], defaults={**{k:v for k,v in guide.items() if k != 'slug'}, 'kind':'test', 'published':True, 'order':order, 'reviewed_at':REVIEWED})
        about=[section('Our introduction','Kashyap Advisors helps students from Nepal explore study opportunities in Italy, from initial planning to settling into university life.'),section('Our story','Our work starts with a student’s goals and the questions that come with studying abroad. We bring those questions into a clear, personal plan.'),section('Our mission','Make the Italy study journey easier to understand through practical, personalised support.'),section('Our vision','Help students make informed educational choices and feel supported in a new country.'),section('Our approach','Understand your profile, explore suitable options, plan applications and stay connected through arrival.'),section('Our team','Meet an advisor at our Basundhara office to discuss your background and study plans.'),section('Why Italy','Italy combines historic academic institutions, varied study options and an international student experience.')]
        add(Page,'About Kashyap Advisors',kind='page',summary='A new country. A big decision. A team by your side.',sections=about)
        add(Page,'Study in Italy',kind='page',summary='Find your place in a country that has inspired the world for centuries.',sections=[section(t,d) for t,d in benefits])
        add(Page,'Student Journey',kind='page',summary='From your first question in Nepal to your first day in Italy.',sections=[section('Type D student visa pathway','Use this planning guide alongside the official international-student procedures. The competent consular authority determines your visa requirements and decision. University and scholarship timelines may overlap.',source_url='https://www.universitaly.it/en/studenti-stranieri')])
        for title in ['Refund Policy','Disclaimer','Payment Method','Terms & Conditions','Privacy Policy','Cookie Policy']:
            body={'Refund Policy':'Refund eligibility depends on the written service agreement and the stage of work completed. Request the applicable terms before making a payment. Third-party charges follow the provider’s own policies.','Disclaimer':'Information supports planning and may change. Universities, scholarship authorities and consular offices make their own decisions. Kashyap Advisors does not guarantee admission, scholarships or visas.','Payment Method':'Request an official invoice and verified payment instructions directly from our office before transferring funds. No account details are published here.','Terms & Conditions':'The scope, fees and terms of consultancy services will be provided in a written agreement before engagement. Contact the office for the applicable terms.','Privacy Policy':'Inquiry details and career applications are used to respond to your request and manage the associated process. Contact headoffice@kashyapadvisors.com to ask about access, correction or deletion. Administrative access is restricted. A complete retention and processing policy must be approved before public launch.','Cookie Policy':'The public site uses local storage to remember cookie preferences and your university comparison list. Django admin uses session and security cookies. External maps and video sites may use their own cookies when opened. No advertising analytics are enabled by default.'}[title]
            add(Page,title,kind='legal',summary='Website information and service policies.',sections=[section(title,body)])
        faqs=[('University Admissions','Can I study in Italy after completing my studies in Nepal?','Your eligibility depends on your qualification, subject and the programme’s current admission call. An advisor can help compare your background with the published requirements.'),('Scholarships','Are scholarships guaranteed?','No. Awards depend on the authority’s eligibility criteria, assessment, available funds and deadlines. We help you understand the process and prepare your application.'),('Visa','Does an admission letter guarantee a student visa?','No. Admission and pre-enrollment support your application, but the competent consular authority makes the visa decision.'),('Documents','Which documents should I prepare first?','Start by gathering your passport, transcripts and qualification certificates. Confirm translation, legalization and recognition requirements for your specific university and visa pathway.'),('Accommodation','Can you help me find accommodation?','We can guide you through residences, scholarship housing and private rental options. Availability and contracts must be confirmed with the provider.'),('Entrance Tests','Do all universities require an entrance test?','No single test applies to every programme. Check each course’s current call for the accepted test, interview or selection process.'),('Tuition Fees','How much will tuition cost?','Fees depend on the programme, institution and any applicable income assessment or reduction. Use the current official fee schedule.'),('Living Costs','How should I plan my monthly budget?','Include rent, utilities, groceries, transport, insurance and personal expenses, plus one-time arrival costs. Get current local quotations for your chosen city.'),('Student Life','Do I need to speak Italian?','Some programmes teach in English, but practical Italian is valuable for daily life. Check the programme’s specific language requirements.'),('Post-Arrival Services','Will I receive support after arriving?','Discuss your support plan before departure. We can guide you through accommodation check-in, university enrollment and the relevant settlement procedures.')]
        for i,(cat,q,a) in enumerate(faqs):FAQ.objects.get_or_create(question=q,defaults=dict(category=cat,answer=a,order=i))
        cats=['Study in Italy','Italian Universities','Scholarships','Visa Updates','University Applications','Entrance Tests','Student Life','Accommodation','Italy Updates','Guides & Resources']
        for title in cats:Category.objects.get_or_create(slug=slugify(title),defaults={'title':title})
        for i,(title,cat,desc) in enumerate([('Your Italy study plan starts here','Study in Italy','Five thoughtful steps to turn a big idea into a practical study plan.'),('Regional scholarships: where to begin','Scholarships','Understand the authority, the call and the documents before you apply.'),('From Nepal to Italy: your arrival checklist','Student Life','A little preparation makes your first weeks in a new country easier.')]):
            add(Article,title,category=Category.objects.get(title=cat),author='Kashyap Advisors Editorial Team',date=date(2026,9,6),summary=desc,image_url=['/assets/italy-hero.jpg','/assets/bologna.jpg','/assets/rome.jpg'][i],sections=[section('Start with the right questions',desc+' Begin by writing down your goals, current qualifications and the decisions you still need to make.'),section('Build your personal checklist','Use official university and authority sources to confirm requirements. Record deadlines, document requests and the next action for each application.'),section('Ask for support when you need it','Bring your shortlist and questions to an advisor. We can help you organise your options and decide what to do next.')])
        self.stdout.write(self.style.SUCCESS('Seeded content. Existing admin edits preserved. No invented testimonials or vacancies.'))
